# FRAGMENT:
#   tasks:
#       -   'highway_merge_2_2_123'

#   # changelane

#   maxTestTime: 50
#   skipExist: False

REPLAY:
  tasks:
    # - '0_495_merge_505'
        # - '0175follow159'
    # - '8_6_2_471'
        # -   '1_909_merge_911'
        # -  '0_571_merge_573'  
        # - '3_370_merge_374'

      # -  '1_699_merge_703'
    #  junction to short
    # -   '1_672_merge_674'
    # -   '10_11_straight_in_adjacent_left_16'
  visualize: True
  skipExist: False