# FRAGMENT:
#   tasks:
#         - '1103cutin46'
#   maxTestTime: 50
#   skipExist: False

REPLAY:
  tasks:
      # too short
      # -  '0_261_merge_271'
      # -  '8_5_2_111'
      # -  '1_672_merge_674'

      # #  out of 
      # -  '5_450_merge_457'
      # #  car lane too long
      -  '0_502_merge_503'

      # -  '3_370_merge_374'
  visualize: True
  skipExist: False