# FRAGMENT:
#   tasks:
#         - 'intersection_12_61_6'
#         - '6_23_left_straight_in_opposite_28'

#         - '5_23_straight_straight_24' 



#   maxTestTime: 50
#   skipExist: False

REPLAY:
  tasks:
        - '2_732_merge_733'
             


  visualize: True
  skipExist: False

# SERIAL:
#   tasks:
#       - "serial_task_1"
#   dt: 0.1
#   maxTestTime: 200
#   skipExist: False