FRAGMENT:
  tasks:
        - '1174follow1084'
        - '8_3_1_347'
        - '8_2_1_28'
        - '5_127_straight_straight_131'
        - '5_23_straight_straight_24'
        - 'highway_merge_2_2_119'
        - '1451follow1327'
        - 'highway_merge_2_2_92'
        - '8_2_1_29'
        - '5_96_straight_in_adjacent_left_106'
        - '0_571_merge_573'
        - '1413follow1296'
  maxTestTime: 25
  skipExist: False


REPLAY:
  tasks:
        - '0779follow719'
        - '1_772_merge_807'
        - '8_3_1_485'
        - '0282follow253'
        - 'intersection_12_61_6'
        - '8_3_1_520'
        - '8_101_straight_straight_102'
        - '0_275_merge_280'
        - '1455lanechanging46'
        - '8_7_1_138'
        - '0142follow132'
        - '13_29_straight_straight_30'
        - 'crossing_952_32_1'
        - '0_879_merge_895'
        - '8_6_4_189'
        - '1_189_merge_197'
        - '1510follow1378'
        - '11_95_straight_straight_101'
        - '0285follow256'
        - '1482follow1354'
        - '0_440_merge_441'
        - '13_117_straight_in_adjacent_left_119'
        - 'highway_merge_2_2_66'
        - '1_747_merge_748'
        - '5_539_merge_546'
        - '0759follow699'
        - 'highway_merge_2_1_446'
        - '0194lanechanging11'
        - '0_137_straight_straight_138'
        - '1496follow1364'
        - '1517follow1385'
        - '1_358_merge_362'
        - '8_5_3_210'
        - '1_515_merge_528'
        - '0216follow194'
        - '8_7_1_408'
        - '2_776_merge_779'
  visualize: False
  skipExist: False
