FRAGMENT:
  tasks:
        - '1174follow1084'
        - '8_3_1_347'
        - '8_2_1_28'
        - '5_127_straight_straight_131'
        - '5_23_straight_straight_24'
        - 'highway_merge_2_2_119'
        - '1451follow1327'
        - 'highway_merge_2_2_92'
        - '8_2_1_29'
        - '5_96_straight_in_adjacent_left_106'
        - '0_571_merge_573'
        - '1413follow1296'
        - '8_2_1_189'
        - '5_53_straight_straight_57'
        - 'highway_merge_2_1_93'
        - '8_2_1_210'
        - '8_3_2_321'
        - '8_2_1_564'
        - '1132follow1048'
        - '1236follow1140'
        - 'highway_merge_3_1_152'
        - '6_23_left_straight_in_opposite_28'
        - '1418follow1301'
        - '5_130_straight_in_opposite_left_136'
  maxTestTime: 25
  skipExist: False


REPLAY:
  tasks:
        - '3_1_straight_straight_2'
        - '0220follow198'
        - '0_1064_merge_1078'
        - '8_6_4_273'
        - '5_69_straight_in_adjacent_left_74'
        - 'highway_merge_2_1_286'
        - '9_21_straight_straight_23'
        - 'highway_merge_2_2_383'
        - '1233follow1137'
        - '0710follow650'
        - '0210cutin11'
        - '8_6_4_248'
        - '0957follow892'
        - '15_83_straight_straight_85'
        - '1_683_merge_686'
        - '0546follow498'
        - '1_841_merge_851'
        - 'highway_merge_2_2_200'
        - '1662follow1520'
        - '5_127_straight_straight_131'
        - '1_1165_merge_1172'
        - '1_4_straight_in_adjacent_left_5'
        - '2_94_merge_97'
        - '1505follow1373'
        - '0_343_merge_347'
        - '13_35_straight_in_adjacent_left_40'
        - '1_316_merge_338'
        - '1347follow1233'
        - '0704follow644'
        - '1_261_merge_305'
        - '0322lanechanging19'
        - '8_5_3_291'
        - '0_1026_merge_1036'
        - '1_970_merge_983'
        - '3_39_straight_in_adjacent_left_43'
        - '3_990_merge_1001'
        - '1466follow1339'
        - '2_732_merge_733'
        - '4_40_straight_straight_42'
        - '0779follow719'
        - '1_772_merge_807'
        - '8_3_1_485'
        - '0282follow253'
        - 'intersection_12_61_6'
        - '8_3_1_520'
        - '8_101_straight_straight_102'
        - '0_275_merge_280'
        - '1455lanechanging46'
        - '8_7_1_138'
        - '0142follow132'
        - '13_29_straight_straight_30'
        - 'crossing_952_32_1'
        - '0_879_merge_895'
        - '8_6_4_189'
        - '1_189_merge_197'
        - '1510follow1378'
        - '11_95_straight_straight_101'
        - '0285follow256'
        - '1482follow1354'
        - '0_440_merge_441'
        - '13_117_straight_in_adjacent_left_119'
        - 'highway_merge_2_2_66'
        - '1_747_merge_748'
        - '5_539_merge_546'
        - '0759follow699'
        - 'highway_merge_2_1_446'
        - '0194lanechanging11'
        - '0_137_straight_straight_138'
        - '1496follow1364'
        - '1517follow1385'
        - '1_358_merge_362'
        - '8_5_3_210'
        - '1_515_merge_528'
        - '0216follow194'
        - '8_7_1_408'
        - '2_776_merge_779'
  visualize: False
  skipExist: False
