FRAGMENT:
  tasks:
        - '8_2_1_189'
        - '5_53_straight_straight_57'
        - 'highway_merge_2_1_93'
        - '8_2_1_210'
        - '8_3_2_321'
        - '8_2_1_564'
        - '1132follow1048'
        - '1236follow1140'
        - 'highway_merge_3_1_152'
        - '6_23_left_straight_in_opposite_28'
        - '1418follow1301'
        - '5_130_straight_in_opposite_left_136'
  maxTestTime: 25
  skipExist: False


REPLAY:
  tasks:
        - '3_1_straight_straight_2'
        - '0220follow198'
        - '0_1064_merge_1078'
        - '8_6_4_273'
        - '5_69_straight_in_adjacent_left_74'
        - 'highway_merge_2_1_286'
        - '9_21_straight_straight_23'
        - 'highway_merge_2_2_383'
        - '1233follow1137'
        - '0710follow650'
        - '0210cutin11'
        - '8_6_4_248'
        - '0957follow892'
        - '15_83_straight_straight_85'
        - '1_683_merge_686'
        - '0546follow498'
        - '1_841_merge_851'
        - 'highway_merge_2_2_200'
        - '1662follow1520'
        - '5_127_straight_straight_131'
        - '1_1165_merge_1172'
        - '1_4_straight_in_adjacent_left_5'
        - '2_94_merge_97'
        - '1505follow1373'
        - '0_343_merge_347'
        - '13_35_straight_in_adjacent_left_40'
        - '1_316_merge_338'
        - '1347follow1233'
        - '0704follow644'
        - '1_261_merge_305'
        - '0322lanechanging19'
        - '8_5_3_291'
        - '0_1026_merge_1036'
        - '1_970_merge_983'
        - '3_39_straight_in_adjacent_left_43'
        - '3_990_merge_1001'
        - '1466follow1339'
        - '2_732_merge_733'
        - '4_40_straight_straight_42'
  visualize: False
  skipExist: False
