# FRAGMENT:
#   tasks:
#         # - '5_23_straight_straight_24'
#         # -  'highway_merge_3_1_152'
#   maxTestTime: 25
#   skipExist: False


REPLAY:
  tasks:
        - '15_83_straight_straight_85'
        # - '4_40_straight_straight_42'
        - '8_5_3_291'
        - '8_6_4_273'

  visualize: True
  skipExist: False
