FRAGMENT:
  tasks:
        - '1103cutin46'
        - '8_2_1_143'
        - '0_150_merge_158'
        - '5_27_straight_in_adjacent_left_29'
        - '1277follow1175'
        - '0_411_merge_421'
        - 'highway_merge_3_1_192'
        - '5_130_straight_in_opposite_left_136'
  maxTestTime: 30
  skipExist: False
REPLAY:
  tasks:
        - '1359follow1244'
        - '0_495_merge_505'
        - '0_860_merge_863'
        - '8_3_1_312'
        - '4_316_merge_320'
        - '6_1688_merge_1718'
        - '0175follow159'
        - '0408follow369'
        - '3_134_straight_straight_142'
        - '9_21_straight_straight_23'
        - '0_496_merge_502'
        - '2_732_merge_733'
        - '6_48_straight_straight_49'
        - '0_402_merge_412'
        - '0272follow243'
        - '0222follow200'
        - '0_499_merge_513'
        - 'highway_merge_2_1_298'
        - '3_370_merge_374'
        - 'highway_merge_2_2_93'
        - '1248follow1150'
        - '0_502_merge_503'
        - 'highway_merge_2_1_185'
        - '8_5_3_81'
        - '8_6_2_471'
        - 'highway_merge_3_1_115'
        - 'highway_merge_2_2_488'
        - '0_261_merge_271'
        - '8_5_2_111'
        - '1_909_merge_911'
        - 'highway_merge_2_2_232'
        - '0_571_merge_573'
        - '0_856_merge_858'
        - '8_5_2_300'
        - '1_699_merge_703'
        - '1_378_merge_382'
        - 'highway_merge_2_2_66'
        - '10_11_straight_in_adjacent_left_16'
        - '1_672_merge_674'
        - '13_19_straight_in_opposite_left_21'
        - '0138follow128'
        - 'highway_merge_2_2_380'
  visualize: False
  skipExist: False