FRAGMENT:
  tasks:
        - '1174follow1084'
        - '8_3_1_54'
        - '5_36_straight_in_adjacent_left_43'
        - 'highway_merge_3_2_61'
        - '1372follow1257'
        - '6_25_straight_straight_26'
        - 'highway_merge_3_2_136'
        - 'highway_merge_2_2_98'
        - '1130follow1046'
        - 'highway_merge_2_1_111'
        - 'highway_merge_2_2_92'
        - 'highway_merge_2_2_115'
        - '8_3_1_347'
        - 'highway_merge_3_1_165'
        - '8_2_1_51'
        - 'highway_merge_2_2_123'
  maxTestTime: 30
  skipExist: True
REPLAY:
  tasks:
        - '14_6_left_left_8'
        - '0690follow631'
        - '8_5_3_365'
        - '14_1_straight_in_adjacent_left_2'
        - '1255follow1156'
        - '1832follow1660'
        - '0_621_merge_623'
        - '3_175_merge_186'
        - '1_257_merge_259'
        - '13_19_straight_in_opposite_left_21'
        - '2_128_merge_133'
        - '0178follow162'
        - '1_576_merge_585'
        - 'highway_merge_3_1_89'
        - '1_621_merge_635'
        - '0_612_merge_619'
        - 'highway_merge_2_2_317'
        - '1842follow1670'
        - '13_117_straight_in_adjacent_left_119'
        - '1618follow1477'
        - '4_12_straight_in_adjacent_left_14'
        - '0325follow293'
        - '0_606_merge_608'
        - '8_5_1_438'
        - '8_1_straight_straight_3'
        - '4_818_merge_828'
        - '5_66_merge_87'
        - 'highway_merge_2_2_488'
        - 'crossing_952_32_1'
        - '1184follow1094'
        - '1_821_merge_824'
        - 'highway_merge_2_2_380'
        - '1223follow1127'
        - '1433cutin76'
  visualize: False
  skipExist: True