# FRAGMENT:
#   tasks:
#         - '1103cutin46'
#   maxTestTime: 50
#   skipExist: False

REPLAY:
  tasks:
        - '9_21_straight_straight_23'
        - '8_5_2_111'
        - '8_5_2_300'

      # - '1_316_merge_338'
      # - '2_101_merge_107'
      # - '5_450_merge_457'
      # 
      # - 'highway_merge_3_1_115'
      # - '0_261_merge_271'
      # - '2_732_merge_733'
      # - '6_1688_merge_1718'

  visualize: True
  skipExist: False