# FRAGMENT:
#   tasks:
#   maxTestTime: 25
  # skipExist: True

# SERIAL:
#   tasks:
#   dt: 0.1
#   maxTestTime: 200
#   skipExist: True

REPLAY:
  tasks:
    - 0_1019_merge_1024
  visualize: True
  skipExist: False
