FRAGMENT:
  tasks:
  - "highway_merge_3_2_61"
  - "8_3_1_541"
  - "highway_merge_2_2_100"
  - "6_64_left_left_66"
  - "8_3_1_555"
  - "8_3_2_286"
  - "highway_merge_3_2_59"
  - "8_3_2_339"
  - "highway_merge_2_1_123"
  - "4_93_straight_straight_95"
  - "highway_merge_2_2_113"
  - "5_93_left_left_104"
  - "8_2_1_445"
  - "highway_merge_3_2_80"
  - "5_50_straight_straight_52"
  - "5_24_straight_straight_25"
  - "highway_merge_2_2_126"
  - "4_68_straight_in_adjacent_left_70"
  - "highway_merge_3_2_121"
  - "highway_merge_2_2_108"
  - "6_24_straight_straight_30"
  - "5_27_straight_in_adjacent_left_29"
  - "7_28_1_16"
  - "highway_merge_3_1_160"
  - "5_130_straight_in_opposite_left_136"
  - "5_96_straight_in_adjacent_left_106"
  - "4_62_straight_straight_63"
  - "5_105_straight_straight_109"
  - "5_40_straight_in_adjacent_left_43"
  - "6_23_left_straight_in_opposite_28"
  - "5_19_straight_straight_21"
  - "5_48_left_straight_in_adjacent_49"
  - "5_3_straight_straight_9"
  - "0_556_merge_573"
  - "4_71_straight_straight_72"
  - "highway_merge_2_2_122"
  - "0_346_merge_357"
  - "highway_merge_2_1_151"
  - "5_36_straight_in_adjacent_left_43"
  - "8_3_1_36"
  - "5_68_straight_straight_70"
  - "highway_merge_3_1_152"
  - "0_354_merge_357"
  - "5_92_straight_in_opposite_left_93"
  - "5_73_straight_straight_75"
  - "8_3_2_255"
  - "6_16_straight_in_adjacent_left_17"
  - "8_2_1_543"
  - "highway_merge_2_1_153"
  - "0_571_merge_573"
  - "5_39_straight_straight_41"
  - "8_2_1_119"
  - "5_115_straight_in_adjacent_left_117"
  - "8_2_1_130"
  - "5_53_straight_straight_57"
  - "6_71_straight_straight_75"
  - "6_63_left_left_66"
  - "6_27_straight_straight_30"
  - "6_25_straight_straight_26"
  - "0_612_merge_617"
  - "5_127_straight_straight_131"
  - "5_118_straight_straight_122"
  - "highway_merge_3_1_192"
  - "highway_merge_2_1_111"
  - "4_75_straight_straight_76"
  - "6_88_straight_straight_96"
  - "0_411_merge_421"
  - "5_129_straight_straight_131"
  - "4_63_straight_in_opposite_left_69"
  - "5_107_straight_straight_113"

  maxTestTime: 25
  # skipExist: True

# SERIAL:
#   tasks:
#   dt: 0.1
#   maxTestTime: 200
#   skipExist: True

# REPLAY:
#   tasks:
#   visualize: False
#   skipExist: True
