REPLAY:
  visualize: False
  skipExist: False
  tasks:
    -   '1_624_merge_640'
    -   '1_631_merge_1550'
    -   '1_672_merge_674'
    -   '1_683_merge_686'
    -   '1_698_merge_699'
    -   '1_699_merge_703'
    -   '1_736_merge_737'
    -   '1_73_merge_81'
    -   '1_747_merge_748'
    -   '1_751_merge_756'
    -   '1_754_merge_761'
    -   '1_767_merge_772'
    -   '1_768_merge_775'
    -   '1_772_merge_807'
    -   '1_77_merge_81'
    -   '1_785_merge_792'
    -   '1_801_merge_832'
    -   '1_818_merge_823'
    -   '1_821_merge_824'
    -   '1_841_merge_851'
    -   '1_86_merge_93'
    -   '1_878_merge_881'
    -   '1_881_merge_887'
    -   '1_883_merge_892'
    -   '1_888_merge_894'
    -   '1_909_merge_911'
    -   '1_911_merge_915'
    -   '1_936_merge_941'
    -   '1_947_merge_949'
    -   '1_951_merge_964'
    -   '1_959_merge_964'
    -   '1_966_merge_970'
    -   '1_970_merge_983'
    -   '1_98_merge_111'
    -   '1_993_merge_1005'
    -   '2_0_merge_4'
    -   '2_100_merge_103'
    -   '2_101_merge_107'
    -   '2_108_merge_121'
    -   '2_128_merge_133'
    -   '2_133_merge_136'
    -   '2_268_merge_270'
    -   '2_26_merge_31'
    -   '2_29_merge_31'
    -   '2_314_merge_315'
    -   '2_3_merge_5'
    -   '2_443_merge_445'
    -   '2_589_merge_597'
    -   '2_732_merge_733'
    -   '2_776_merge_779'
    -   '2_86_merge_102'
    -   '2_89_merge_94'
    -   '2_94_merge_97'
    -   '2_99_merge_103'
    -   '3_10_merge_39'
    -   '3_126_straight_straight_127'
    -   '3_134_straight_straight_142'
    -   '3_175_merge_186'
    -   '3_199_merge_203'
    -   '3_1_straight_straight_2'
    -   '3_224_merge_227'
    -   '3_370_merge_374'
    -   '3_39_straight_in_adjacent_left_43'
    -   '3_402_merge_414'
    -   '3_412_merge_414'
    -   '3_428_merge_444'
    -   '3_555_merge_560'
    -   '3_56_merge_63'
    -   '3_72_merge_83'
    -   '3_748_merge_760'
    -   '3_81_merge_83'
    -   '3_990_merge_1001'
    -   '3_9_straight_in_adjacent_left_13'
    -   '4_12_straight_in_adjacent_left_14'
    -   '4_206_merge_211'
    -   '4_22_straight_in_opposite_left_24'
    -   '4_294_merge_296'
    -   '4_316_merge_320'
    -   '4_353_merge_355'
    -   '4_37_straight_in_adjacent_left_38'
    -   '4_393_merge_399'
    -   '4_40_straight_straight_42'
    -   '4_42_merge_44'
    -   '4_44_straight_straight_45'
    -   '4_57_straight_in_opposite_left_58'
    -   '4_59_straight_in_adjacent_left_60'
    -   '4_640_merge_655'
    -   '4_648_merge_677'
    -   '4_657_merge_685'
    -   '4_680_merge_705'
    -   '4_702_merge_708'
    -   '4_73_straight_in_adjacent_left_74'
    -   '4_75_straight_straight_76'
    -   '4_804_merge_811'
    -   '4_818_merge_828'
    -   '4_850_merge_851'
    -   '4_91_straight_straight_98'
    -   '4_93_straight_straight_95'
    -   '5_127_straight_straight_131'
    -   '5_194_merge_226'
    -   '5_19_straight_straight_21'
    -   '5_27_straight_in_adjacent_left_29'
    -   '5_413_merge_418'
    -   '5_450_merge_457'
    -   '5_465_merge_476'
    -   '5_519_merge_566'
    -   '5_52_merge_55'
    -   '5_539_merge_546'
    -   '5_66_merge_87'
    -   '5_69_straight_in_adjacent_left_74'
    -   '5_73_straight_straight_75'
    -   '5_819_merge_826'
    -   '5_848_merge_856'
    -   '5_919_merge_921'
    -   '6_1363_merge_1429'
    -   '6_1391_merge_1429'
    -   '6_1535_merge_1540'
    -   '6_1688_merge_1718'
    -   '6_187_merge_212'
    -   '6_2063_merge_2093'
    -   '6_2339_merge_2341'
    -   '6_2620_merge_2649'
    -   '6_286_merge_325'
    -   '6_390_merge_399'
    -   '6_48_straight_straight_49'
    -   '6_792_merge_854'
    -   '7_178_merge_182'
    -   '7_253_merge_271'
    -   '7_287_merge_311'
    -   '7_28_straight_straight_29'
    -   '7_295_merge_311'
    -   '7_39_straight_straight_40'
    -   '7_41_straight_straight_44'
    -   '7_72_straight_straight_75'
    -   '8_101_straight_straight_102'
    -   '8_109_straight_in_opposite_left_113'
    -   '8_1_straight_straight_3'
    -   '8_3_1_233'
    -   '8_3_1_237'
    -   '8_3_1_312'
    -   '8_3_1_485'
    -   '8_3_1_520'
    -   '8_3_2_223'
    -   '8_3_2_264'
    -   '8_3_2_272'
    -   '8_3_2_534'
    -   '8_3_2_565'
    -   '8_3_3_364'
    -   '8_3_3_407'
    -   '8_3_3_74'
    -   '8_3_4_458'
    -   '8_3_4_516'
    -   '8_50_straight_straight_51'
    -   '8_51_straight_straight_54'
    -   '8_55_straight_straight_58'
    -   '8_5_1_138'
    -   '8_5_1_326'
    -   '8_5_1_377'
    -   '8_5_1_41'
    -   '8_5_1_438'