# FRAGMENT:
#   tasks:
#   maxTestTime: 25
  # skipExist: True

# SERIAL:
#   tasks:
#   dt: 0.1
#   maxTestTime: 200
#   skipExist: True

REPLAY:
  tasks:
    - 12_107_straight_straight_113
  visualize: False
  skipExist: True
