# FRAGMENT:
#   tasks:
#         - '1103cutin46'
#   maxTestTime: 50
#   skipExist: False

REPLAY:
  tasks:
      - '1396follow1280'
      - '2_133_merge_136'
      - '1665follow1523'
      - '1255follow1156'
      - '0_623_merge_624'
      - '0_997_merge_1005'

  visualize: False
  skipExist: False